/**
 * Adopter documentation generators (SPEC §11.2, WP-GDPR-SCAFFOLD).
 *
 * These are OPTIONAL scaffolding helpers for open-source adopters operating in
 * stricter jurisdictions. They produce markdown templates that MUST be reviewed
 * and completed by the adopter and routed through qualified data-protection
 * counsel before any EU/UK compliance claim is made (WP-LEGAL).
 *
 * ⚠ AT-REST ENCRYPTION NOTE (honest statement per SPEC §6.5):
 *   node:sqlite (Node ≥ 22 built-in) does NOT support SQLCipher. There is no
 *   built-in column- or page-level encryption in this SQLite backend.
 *   The recommended at-rest controls are:
 *     1. OS-level full-disk encryption (e.g. FileVault, BitLocker, LUKS) — the
 *        strongest practical control for a developer-laptop local store.
 *     2. Restrictive file permissions (0600 on the DB file).
 *     3. Keychain-resident DB path so the file is stored under an encrypted
 *        volume managed by the OS keychain daemon.
 *   Do NOT claim SQLCipher or equivalent page-level encryption unless you
 *   replace the NodeSqliteStore backend with a SQLCipher-capable driver.
 *
 * These functions are NOT legal advice. They return non-empty markdown strings
 * that serve as a starting point only.
 */

export interface DpiaTemplateOptions {
  /** Name of the organisation / product deploying lazy-flow. */
  orgName?: string
  /** ISO-8601 date for the assessment. */
  assessmentDate?: string
}

/**
 * Generate a DPIA (Data Protection Impact Assessment) template in Markdown.
 *
 * The returned document follows the ICO's recommended DPIA structure. Sections
 * marked [TODO] MUST be completed by the adopter and reviewed by a qualified
 * data-protection officer before EU/UK deployment.
 */
export function generateDpiaTemplate(opts: DpiaTemplateOptions = {}): string {
  const org = opts.orgName ?? '[YOUR ORGANISATION]'
  const date = opts.assessmentDate ?? '[ASSESSMENT DATE]'
  return `# Data Protection Impact Assessment (DPIA)

**Organisation:** ${org}
**Product:** lazy-flow (software delivery intelligence platform)
**Assessment date:** ${date}
**Status:** DRAFT — requires DPO review before deployment

> ⚠ This document was generated by lazy-flow's GDPR scaffolding helpers.
> It is a starting point only and is NOT legal advice. Route through qualified
> data-protection counsel before making any compliance claim.

---

## 1. Overview and necessity

lazy-flow ingests GitHub and Jira activity data to compute software-delivery
metrics. Data is stored locally on the installing machine in a SQLite database.

**Processing purpose:** software delivery analytics for engineering teams.
**Necessity assessment:** [TODO — describe why this processing is necessary and
  why less privacy-invasive alternatives were considered and rejected.]

---

## 2. Consultation

**Internal DPO consulted:** [TODO — name / date]
**External counsel consulted:** [TODO — name / date, especially for EU/UK use]

---

## 3. Data flows

| Data category         | Source       | Retention          | Legal basis |
|-----------------------|--------------|--------------------|-------------|
| GitHub login / email  | GitHub API   | ${`[TODO — days]`}         | [TODO]      |
| Jira accountId        | Jira API     | ${`[TODO — days]`}         | [TODO]      |
| Commit metadata       | GitHub API   | ${`[TODO — days]`}         | [TODO]      |
| PR / issue text       | GitHub/Jira  | Scrubbed at ingest | [TODO]      |

> **Note on at-rest encryption:** lazy-flow uses node:sqlite which does NOT
> support SQLCipher. Recommended control: OS-level full-disk encryption +
> restrictive DB file permissions (0600). See code comment in templates.ts.

---

## 4. Risks and mitigations

| Risk                             | Likelihood | Impact | Mitigation                          |
|----------------------------------|------------|--------|-------------------------------------|
| Secrets in PR/issue bodies       | Medium     | High   | WP-SCRUB: scrubbed before storage   |
| Re-identification via email hash | High       | High   | Keyed HMAC (§6.5); hash alone NOT used |
| Cross-org data mixing            | Low        | High   | org_id-bound DB; hard-errors on mix |
| Subject data retained post-exit  | Medium     | Medium | erasePerson() + retention config    |

---

## 5. Lawful basis

**Proposed basis:** [TODO — Legitimate Interest / Consent / Contract]

> ⚠ Employee consent is generally NOT a valid legal basis (power imbalance).
> If deploying in EU/UK, route legal-basis determination through counsel.

---

## 6. Subject rights

| Right          | How supported                                         |
|----------------|-------------------------------------------------------|
| Erasure (Art.17) | \`erasePerson(store, personId)\` cascade removes data |
| Access (Art.15)  | [TODO — describe how subjects can access their data]  |
| Portability      | [TODO]                                                |
| Objection        | [TODO]                                                |

---

## 7. Sign-off

**DPO sign-off:** _________________________________ Date: ___________
**Legal counsel:** _________________________________ Date: ___________
`
}

/**
 * Generate a Legitimate Interest Assessment (LIA) template in Markdown.
 *
 * Required when Legitimate Interest is the proposed legal basis. The three-part
 * test (purpose / necessity / balancing) must be completed by the adopter.
 */
export function generateLiaTemplate(opts: DpiaTemplateOptions = {}): string {
  const org = opts.orgName ?? '[YOUR ORGANISATION]'
  const date = opts.assessmentDate ?? '[ASSESSMENT DATE]'
  return `# Legitimate Interest Assessment (LIA)

**Organisation:** ${org}
**Product:** lazy-flow
**Assessment date:** ${date}
**Status:** DRAFT — requires DPO/legal review

> ⚠ This document is scaffolding generated by lazy-flow. It is NOT legal advice.

---

## Part 1 — Purpose test

**Legitimate interest pursued:**
Software delivery analytics to improve engineering effectiveness and identify
systemic delivery bottlenecks.

**Specific purpose(s):** [TODO — be precise; vague purposes fail the test]

---

## Part 2 — Necessity test

Is the processing of personal data (GitHub logins, Jira accountIds, commit
metadata) necessary to achieve the stated purpose, or could a less
privacy-invasive means achieve the same result?

[TODO — address each data category]

---

## Part 3 — Balancing test

| Factor                          | Assessment                                      |
|---------------------------------|-------------------------------------------------|
| Nature of data                  | Professional activity data; not special-category |
| Reasonable expectation          | [TODO — do engineers expect this analysis?]     |
| Impact on data subjects         | [TODO — potential for performance surveillance?] |
| Safeguards applied              | Pseudonymisation, scrubbing, erasure, retention |
| Opt-out / objection mechanism   | [TODO]                                          |

**Conclusion:** [TODO — does legitimate interest outweigh subject interests?]

---

## Sign-off

**DPO:** _________________________________ Date: ___________
`
}

/**
 * Generate a Transparency Notice template in Markdown.
 *
 * This should be shared with data subjects (engineers) before or at the time
 * data processing begins, per GDPR Arts. 13–14.
 */
export function generateTransparencyNotice(opts: DpiaTemplateOptions = {}): string {
  const org = opts.orgName ?? '[YOUR ORGANISATION]'
  const date = opts.assessmentDate ?? '[DATE]'
  return `# Data Processing Transparency Notice

**Organisation:** ${org}
**Effective date:** ${date}

This notice explains how ${org} processes personal data when using lazy-flow,
an open-source software delivery analytics tool.

---

## What data we collect

lazy-flow ingests data from GitHub and Jira that you have already made
available to your organisation:

- GitHub usernames, commit email addresses, and pull-request activity.
- Jira accountIds and issue activity (transitions, comments).
- Code metadata (file paths, line counts) — never file contents.

**We do NOT collect:** passwords, private messages, or data outside your
organisation's GitHub/Jira scopes.

---

## How we use it

To compute software-delivery metrics (cycle time, review latency, deployment
frequency) for engineering team health — not for individual performance ranking.
[TODO — tailor to your specific use case]

---

## How we protect it

- **Secret scrubbing:** free-text bodies are scrubbed of tokens, API keys, and
  email addresses before storage (WP-SCRUB).
- **Pseudonymisation:** where wanted, emails/accountIds are replaced with a
  keyed HMAC whose key is stored only in the OS keychain.
- **At-rest protection:** [TODO — describe your FDE/file-permission controls;
  note that node:sqlite does NOT provide SQLCipher encryption built-in].
- **Retention:** data older than [TODO — N days] is pruned automatically.

---

## Your rights

You have the right to access, correct, or request erasure of your personal
data. Contact [TODO — DPO contact] to exercise these rights.

---

## Legal basis

[TODO — state your legal basis here; see the accompanying LIA]

> ⚠ This notice is generated scaffolding and requires legal review before use.
`
}
